# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160327_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspaces',
            name='space_type',
            field=models.IntegerField(choices=[(1, 'namespace'), (2, 'tenant')], max_length=256),
        ),
    ]
