# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0005_auto_20160424_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubspaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_url', models.URLField()),
                ('space_name', models.CharField(max_length=255)),
                ('space_type', models.IntegerField(choices=[(1, 'namespace'), (2, 'tenant')])),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Subspaces',
            },
        ),
        migrations.RemoveField(
            model_name='userspaces',
            name='parent_space',
        ),
        migrations.AlterField(
            model_name='userspaces',
            name='space_type',
            field=models.IntegerField(choices=[(1, 'namespace'), (2, 'tenant')]),
        ),
        migrations.AddField(
            model_name='usersubspaces',
            name='parent_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.UserSpaces'),
        ),
        migrations.AddField(
            model_name='usersubspaces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
